#!/usr/bin/env python -B

'''
Usage: rfc2mobi [options] <rfcXXXX|url>

A program to convert RFC or I-D to mobi formatted eBooks.
Options:
  -k ..., --kindlegen=...  The kindlegen program to use. By default, it's "./kindlegen"
  -h, --help
  -f, --file=... The file to read instead of fetching a link

If you want to convert a RFC, just give the RFC name as command line option.
For I-D, specific the link where it can download. 
'''

'''
Created on May 31, 2011
@author: rhuang
'''

import urllib2, urllib, sys, os, getopt, io, subprocess
import shutil
from html import Html

def rfc2mobi(kgen, doc, lines):
        
    #making directory structure
    #TODO: make the directory structure not dependent on rfc number
    if not os.path.exists(doc):
        os.makedirs(doc)

    output = open(os.path.join(doc, doc+'.html'), 'w')
    
    html = Html('%s' %(doc), lines, output)
    html.createHTML()
    output.close()

    #using kindlegen binary to create .mobi file
    exitCode = subprocess.call([kgen, os.path.join(doc, doc+'.html'), '-o', doc+".mobi"])
    if exitCode >= 2:
        print "Fatal error while processing %s." %(doc)
        print "Deleting attempted directory %s." %(doc)
        shutil.rmtree(doc)
    else:  
        print "Successfully converted %s into %s directory." % (doc, doc)

def usage():
     print __doc__

kgen=os.path.join("./", "kindlegen")


def getlines(doc, link, file):
    final_lines = []

    if file is None:
        print ""
        print "link = %s, rfc was = %s" % (link, doc)
        req = urllib2.Request(link)
        req.add_header('User-Agent', 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-GB; rv:1.9.0.3) Gecko/2008092417 Firefox/3.0.3')
        response = urllib2.urlopen(req)
        for line in response:
            final_lines.append(line)
        response.close()
    elif not os.path.exists(file):
        print "Failed to fetch from file, but we were given the option for it! bailing..."
        exit(1)
    else:
        with open(file,'r') as myfile:
            final_lines = myfile.readlines()
    return final_lines
    
if __name__ == '__main__':
    
    try:
      opts, args = getopt.getopt(sys.argv[1:], "hk:f:", ["help", "kindlegen=","rfc-file="])
    except getopt.GetoptError:
      usage()
      sys.exit(2)

    file = None
    
    for opt, arg in opts:
      if opt in ("-h", "--help"):
        usage()
        sys.exit()
      elif opt in ("-k", "--kindlegen"):
        kgen=arg
      elif opt in ("-f", "--rfc-file"):
        file=arg
        print "file was " + file

    if len(sys.argv) < 2:
      usage()
      sys.exit()

    if sys.argv[-1].lower().startswith('rfc'):
        doc = sys.argv[-1].lower()
        link = 'http://www.ietf.org/rfc/%s.txt' % (doc)
    else:
        link = sys.argv[-1]
        doc = sys.argv[-1].split('/')[-1]

    #arguments are cleaned up, fetch the actual lines we will process
    lines = getlines(doc,link,file)

    rfc2mobi(kgen, doc, lines)
